version: '3.8'

services:
  xampp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./cscs:/opt/lampp/htdocs  # CONFIGURA EL VOLUMEN COMO QUIERAS
